-- Net trabfinal - IOPT
-- Automatic code generated by IOPT2VHDL XSLT transformation.
-- by GRES Research Group - 2015 


Library IEEE;
Use IEEE.STD_LOGIC_1164.ALL;
Use IEEE.STD_LOGIC_ARITH.ALL;
Use IEEE.STD_LOGIC_UNSIGNED.ALL;


Entity trabfinal_main IS
Port(
    Clk : IN STD_LOGIC;
    Enable : IN STD_LOGIC;
    Reset : IN STD_LOGIC
);
End trabfinal_main;



Architecture Structural OF trabfinal_main IS

  -- Component Definition:
  Component trabfinal IS
  Port(
      Clk : IN STD_LOGIC;
      PRES1_IN1 : IN STD_LOGIC;
      PRES2_IN1 : IN STD_LOGIC;
      TICKET_IN1 : IN STD_LOGIC;
      PRES1_OUT1 : IN STD_LOGIC;
      PRES2_OUT1 : IN STD_LOGIC;
      TICKET_OUT1 : IN STD_LOGIC;
      PRES1_IN2 : IN STD_LOGIC;
      PRES2_IN2 : IN STD_LOGIC;
      TICKET_IN2 : IN STD_LOGIC;
      PRES1_OUT2 : IN STD_LOGIC;
      PRES2_OUT2 : IN STD_LOGIC;
      TICKET_OUT2 : IN STD_LOGIC;
      PRES1_OUT3 : IN STD_LOGIC;
      PRES2_OUT3 : IN STD_LOGIC;
      TICKET_OUT3 : IN STD_LOGIC;
      AND01a : IN STD_LOGIC;
      AND01b : IN STD_LOGIC;
      Park0 : IN STD_LOGIC;
      Unpark0 : IN STD_LOGIC;
      Park1 : IN STD_LOGIC;
      Unpark1 : IN STD_LOGIC;
      CANC_IN1 : OUT STD_LOGIC;
      CANC_OUT1 : OUT STD_LOGIC;
      CANC_IN2 : OUT STD_LOGIC;
      CANC_OUT2 : OUT STD_LOGIC;
      CANC_OUT3 : OUT STD_LOGIC;
      CAPT : OUT INTEGER RANGE 0 TO 100;
      CAP0 : OUT INTEGER RANGE 0 TO 50;
      CAP1 : OUT INTEGER RANGE 0 TO 50;
      CIRC0 : OUT INTEGER RANGE 0 TO 100;
      CIRC1 : OUT INTEGER RANGE 0 TO 100;
      Enable : IN STD_LOGIC;
      Reset : IN STD_LOGIC
  );
  End Component trabfinal;

  -- Internal signals:

BEGIN

    U_trabfinal : trabfinal Port Map(
        Clk => Clk,
        PRES1_IN1 => '0',
        PRES2_IN1 => '0',
        TICKET_IN1 => '0',
        PRES1_OUT1 => '0',
        PRES2_OUT1 => '0',
        TICKET_OUT1 => '0',
        PRES1_IN2 => '0',
        PRES2_IN2 => '0',
        TICKET_IN2 => '0',
        PRES1_OUT2 => '0',
        PRES2_OUT2 => '0',
        TICKET_OUT2 => '0',
        PRES1_OUT3 => '0',
        PRES2_OUT3 => '0',
        TICKET_OUT3 => '0',
        AND01a => '0',
        AND01b => '0',
        Park0 => '0',
        Unpark0 => '0',
        Park1 => '0',
        Unpark1 => '0',
        Enable => Enable,
        Reset => Reset
    );

End Structural;
